import React from "react";
import { EditableText } from '../../EditableText';
import { BaseComponentProps } from '../../RendererRegistry';


export const Footer: React.FC<BaseComponentProps> = ({ data, theme, slideId, componentId, assets }) => (
  <div className="mt-auto w-full pt-4 border-t border-white/10 text-[clamp(0.7rem,1cqw,0.875rem)] opacity-50 flex justify-between"><span>{data.content || data.text || "Generated by Orivox V3"}</span><span>{data.show_slide_number ? "Page" : ""}</span></div>
);
