import { PresentationIR } from "@/types/presentation-ir.types";
import { SharedMemory, SharedMemoryContext } from "./SharedMemory";
import { AssetCache, CachedAsset } from "./AssetCache";

/**
 * Immutable wrapper around the Presentation IR.
 * Every mutation creates a new instance to prevent side-effects.
 */
export class WorkflowState {
  private readonly _ir: PresentationIR;
  private readonly _sharedMemory: SharedMemory;
  private readonly _assetCache: AssetCache;
  
  // Ephemeral state generated by agents that hasn't made it into final IR yet
  private readonly _ephemeralState: Record<string, any>;

  constructor(
    initialIR: PresentationIR, 
    ephemeralState: Record<string, any> = {},
    sharedMemory: SharedMemory = new SharedMemory(),
    assetCache: AssetCache = new AssetCache()
  ) {
    // Deep clone to guarantee immutability (in a real app, use structuredClone or Immutable.js)
    this._ir = JSON.parse(JSON.stringify(initialIR));
    this._ephemeralState = JSON.parse(JSON.stringify(ephemeralState));
    this._sharedMemory = sharedMemory;
    this._assetCache = assetCache;
  }

  public get ir(): PresentationIR {
    return this._ir; // Would return a deep clone in strict environments
  }

  public getEphemeral<T>(key: string): T | undefined {
    return this._ephemeralState[key];
  }

  public get sharedMemory(): SharedMemory {
    return this._sharedMemory;
  }

  public get assetCache(): AssetCache {
    return this._assetCache;
  }

  /**
   * Mutate IR returning a new immutable state.
   */
  public updateIR(mutator: (draft: PresentationIR) => void): WorkflowState {
    const nextIR = JSON.parse(JSON.stringify(this._ir));
    mutator(nextIR);
    return new WorkflowState(nextIR, this._ephemeralState, this._sharedMemory, this._assetCache);
  }

  /**
   * Mutate ephemeral state returning a new immutable state.
   */
  public updateEphemeral(key: string, data: any): WorkflowState {
    const nextEphemeral = { ...this._ephemeralState, [key]: data };
    return new WorkflowState(this._ir, nextEphemeral, this._sharedMemory, this._assetCache);
  }

  /**
   * Update shared memory returning a new immutable state.
   */
  public updateSharedMemory(updates: Partial<SharedMemoryContext>): WorkflowState {
    return new WorkflowState(this._ir, this._ephemeralState, this._sharedMemory.update(updates), this._assetCache);
  }

  /**
   * Save an asset to the cache returning a new immutable state.
   */
  public cacheAsset(asset: CachedAsset): WorkflowState {
    return new WorkflowState(this._ir, this._ephemeralState, this._sharedMemory, this._assetCache.saveAsset(asset));
  }
}
