/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIdRouteImport } from './routes/workspace.$id'
import { Route as PresentIdRouteImport } from './routes/present.$id'
import { Route as ExportIdRouteImport } from './routes/export.$id'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPresentationsRouteImport } from './routes/_app.presentations'
import { Route as AppHomeRouteImport } from './routes/_app.home'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdRoute = WorkspaceIdRouteImport.update({
  id: '/workspace/$id',
  path: '/workspace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentIdRoute = PresentIdRouteImport.update({
  id: '/present/$id',
  path: '/present/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportIdRoute = ExportIdRouteImport.update({
  id: '/export/$id',
  path: '/export/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPresentationsRoute = AppPresentationsRouteImport.update({
  id: '/presentations',
  path: '/presentations',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AppHomeRoute
  '/presentations': typeof AppPresentationsRoute
  '/settings': typeof AppSettingsRoute
  '/export/$id': typeof ExportIdRoute
  '/present/$id': typeof PresentIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AppHomeRoute
  '/presentations': typeof AppPresentationsRoute
  '/settings': typeof AppSettingsRoute
  '/export/$id': typeof ExportIdRoute
  '/present/$id': typeof PresentIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/presentations': typeof AppPresentationsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/export/$id': typeof ExportIdRoute
  '/present/$id': typeof PresentIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/presentations'
    | '/settings'
    | '/export/$id'
    | '/present/$id'
    | '/workspace/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/presentations'
    | '/settings'
    | '/export/$id'
    | '/present/$id'
    | '/workspace/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/home'
    | '/_app/presentations'
    | '/_app/settings'
    | '/export/$id'
    | '/present/$id'
    | '/workspace/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ExportIdRoute: typeof ExportIdRoute
  PresentIdRoute: typeof PresentIdRoute
  WorkspaceIdRoute: typeof WorkspaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$id': {
      id: '/workspace/$id'
      path: '/workspace/$id'
      fullPath: '/workspace/$id'
      preLoaderRoute: typeof WorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/$id': {
      id: '/present/$id'
      path: '/present/$id'
      fullPath: '/present/$id'
      preLoaderRoute: typeof PresentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export/$id': {
      id: '/export/$id'
      path: '/export/$id'
      fullPath: '/export/$id'
      preLoaderRoute: typeof ExportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/presentations': {
      id: '/_app/presentations'
      path: '/presentations'
      fullPath: '/presentations'
      preLoaderRoute: typeof AppPresentationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppPresentationsRoute: typeof AppPresentationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppPresentationsRoute: AppPresentationsRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ExportIdRoute: ExportIdRoute,
  PresentIdRoute: PresentIdRoute,
  WorkspaceIdRoute: WorkspaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
